/**
 * The complete set of error codes the API may return. Codes are stable
 * identifiers meant to be branched on by clients; `message` is for humans and
 * may change.
 */
export const ERROR_CODES = {
  // 400
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  UNSUPPORTED_LANGUAGE: 'UNSUPPORTED_LANGUAGE',
  INVALID_PROJECT_PATH: 'INVALID_PROJECT_PATH',

  // 403 — the local filesystem boundary
  FILESYSTEM_ACCESS_DISABLED: 'FILESYSTEM_ACCESS_DISABLED',
  DIRECTORY_NOT_READABLE: 'DIRECTORY_NOT_READABLE',
  /** A source path that resolved outside the project's own repository root. */
  SOURCE_PATH_NOT_ALLOWED: 'SOURCE_PATH_NOT_ALLOWED',
  SOURCE_NOT_READABLE: 'SOURCE_NOT_READABLE',

  // 404
  NOT_FOUND: 'NOT_FOUND',
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
  REPOSITORY_NOT_FOUND: 'REPOSITORY_NOT_FOUND',
  ANALYSIS_NOT_FOUND: 'ANALYSIS_NOT_FOUND',
  NODE_NOT_FOUND: 'NODE_NOT_FOUND',
  REPOSITORY_PATH_NOT_FOUND: 'REPOSITORY_PATH_NOT_FOUND',
  DIRECTORY_NOT_FOUND: 'DIRECTORY_NOT_FOUND',
  SOURCE_FILE_NOT_FOUND: 'SOURCE_FILE_NOT_FOUND',

  // 409
  CONFLICT: 'CONFLICT',
  ANALYSIS_ALREADY_RUNNING: 'ANALYSIS_ALREADY_RUNNING',
  REPOSITORY_NOT_CONFIGURED: 'REPOSITORY_NOT_CONFIGURED',

  // 422 / pipeline failures surfaced through analysis job records
  LANGUAGE_DETECTION_FAILED: 'LANGUAGE_DETECTION_FAILED',
  SCIP_INDEXER_NOT_FOUND: 'SCIP_INDEXER_NOT_FOUND',
  SCIP_INDEX_FAILED: 'SCIP_INDEX_FAILED',
  SCIP_PARSE_FAILED: 'SCIP_PARSE_FAILED',
  GRAPH_BUILD_FAILED: 'GRAPH_BUILD_FAILED',
  NO_SOURCE_FILES: 'NO_SOURCE_FILES',
  SOURCE_FILE_TOO_LARGE: 'SOURCE_FILE_TOO_LARGE',

  // 501
  DIRECTORY_PICKER_UNAVAILABLE: 'DIRECTORY_PICKER_UNAVAILABLE',

  // 500
  DATABASE_ERROR: 'DATABASE_ERROR',
  CONFIGURATION_ERROR: 'CONFIGURATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/** Default HTTP status for each error code, used by the API error handler. */
export const ERROR_CODE_STATUS: Record<ErrorCode, number> = {
  VALIDATION_ERROR: 400,
  BAD_REQUEST: 400,
  UNSUPPORTED_LANGUAGE: 400,
  INVALID_PROJECT_PATH: 400,

  FILESYSTEM_ACCESS_DISABLED: 403,
  DIRECTORY_NOT_READABLE: 403,
  SOURCE_PATH_NOT_ALLOWED: 403,
  SOURCE_NOT_READABLE: 403,

  NOT_FOUND: 404,
  PROJECT_NOT_FOUND: 404,
  REPOSITORY_NOT_FOUND: 404,
  ANALYSIS_NOT_FOUND: 404,
  NODE_NOT_FOUND: 404,
  REPOSITORY_PATH_NOT_FOUND: 404,
  DIRECTORY_NOT_FOUND: 404,
  SOURCE_FILE_NOT_FOUND: 404,

  CONFLICT: 409,
  ANALYSIS_ALREADY_RUNNING: 409,
  REPOSITORY_NOT_CONFIGURED: 409,

  LANGUAGE_DETECTION_FAILED: 422,
  SCIP_INDEXER_NOT_FOUND: 422,
  SCIP_INDEX_FAILED: 422,
  SCIP_PARSE_FAILED: 422,
  GRAPH_BUILD_FAILED: 422,
  NO_SOURCE_FILES: 422,
  SOURCE_FILE_TOO_LARGE: 422,

  DIRECTORY_PICKER_UNAVAILABLE: 501,

  DATABASE_ERROR: 500,
  CONFIGURATION_ERROR: 500,
  INTERNAL_ERROR: 500,
};
